# Generated by Django 5.0 on 2024-02-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webklas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='bobot_pendapatan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='bobot_pengalaman',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='bobot_pt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='bobot_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='desa',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='kecamatan',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='label',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='nama',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='nik',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='pendapatan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='person',
            name='pengalaman',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='profesi_tambahan',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='profesi_utama',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
