# Generated by Django 5.0 on 2024-03-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webklas', '0004_person_bobot_pendapatan_normalized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bobot_pendapatan_input',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='bobot_pengalaman_input',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='bobot_pt_input',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='bobot_status_input',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
