# Generated by Django 5.0 on 2024-03-05 06:16

import webklas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webklas', '0007_person_hasil_klasifikasi_person_is_newly_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='no',
            field=models.IntegerField(default=webklas.models.get_next_person_number, null=True),
        ),
    ]
